### ISSUE TITLE
Unknown Command for fastboot oem reboot recovery

### ISSUE THREAD

**Issue by DR1Zlol** [ByteOfAllTrades/ONN-Tablet-Hacking#4]
I'm not sure you'll respond since this was 2 years ago, but I've been good for every step except "fastboot oem reboot recovery" after "fastboot flash recovery **twrp.img file name**" whenever I type it into CMD it says unknown command. I have also tried fastboot oem reboot-recovery. I'm not sure why, I've googled a ton and cannot find anything. Please help. :)

**Comment by McGamezZPlayer** [comment]
Hey, I fixed the guide back in August and made a PR, it is still there

**Comment by DR1Zlol** [comment]
I saw that, I followed yours and still no luck. I still get stuck on 'fastboot oem reboot-recovery'.

**Comment by McGamezZPlayer** [comment]
Any error being thrown?
